from typing import List, Optional

from pydantic import BaseModel, Field


class UserStory(BaseModel):
    story: str = Field(description="The user story title")
    user_persona: str = Field(description="The user persona, e.g., 'health-conscious individual'")
    industry: str = Field(
        description="The industry the product would be in, e.g., 'Health and Wellness', 'Entertainment', etc."
    )


class UserStoryExample(BaseModel):
    input: str = Field(description="The idea for the user story")
    tool_calls: List[UserStory] = Field(description="The user stories generated by the tool")
    tool_outputs: Optional[List[str]] = Field(description="The outputs of the tool calls", default=None)


def get_user_story_examples():
    examples: List[UserStoryExample] = []

    examples.append(
        UserStoryExample(
            input="Create an app that helps users track their daily water intake",
            tool_calls=[
                UserStory(
                    story="As a user, I want to track my daily water intake so that I can stay hydrated throughout the day",
                    user_persona="health-conscious individual",
                    industry="Health and Wellness",
                )
            ],
        )
    )

    examples.append(
        UserStoryExample(
            input="Develop a platform that helps small businesses manage their finances",
            tool_calls=[
                UserStory(
                    story="As a small business owner, I want to manage my finances efficiently so that I can keep track of expenses and profits.",
                    user_persona="small business owner",
                    industry="Finance and Accounting",
                )
            ],
        )
    )

    examples.append(
        UserStoryExample(
            input="Create a tool that assists remote teams in collaborating on projects",
            tool_calls=[
                UserStory(
                    story="As a remote team member, I want to collaborate on projects seamlessly so that I can stay aligned with my team and meet deadlines.",
                    user_persona="remote team member",
                    industry="Collaboration and Productivity",
                )
            ],
        )
    )

    examples.append(
        UserStoryExample(
            input="Build a service that allows people to rent out their parking spaces",
            tool_calls=[
                UserStory(
                    story="As a city driver, I want to easily find and rent parking spaces so that I can park conveniently without searching for hours.",
                    user_persona="city driver",
                    industry="Transportation and Real Estate",
                )
            ],
        )
    )

    examples.append(
        UserStoryExample(
            input="Design an app that provides personalized fitness routines for users",
            tool_calls=[
                UserStory(
                    story="As a fitness enthusiast, I want personalized workout routines so that I can improve my strength and achieve my fitness goals.",
                    user_persona="fitness enthusiast",
                    industry="Fitness and Wellness",
                )
            ],
        )
    )

    examples.append(
        UserStoryExample(
            input="Create an AI-based tool that helps job seekers optimize their resumes",
            tool_calls=[
                UserStory(
                    story="As a job seeker, I want to optimize my resume using AI so that I can increase my chances of landing my ideal job.",
                    user_persona="job seeker",
                    industry="Career Services and Technology",
                )
            ],
        )
    )

    return examples
